data:
  data_dir: ../Autopet
  splits_file: ../Autopet/splits_final.json
  fold: 0
  target_shape: [ 128, 160, 112 ]
  batch_size: 2
  suffix: .npz
  num_workers_train: 24
  num_workers_val: 24
  data_dir_preprocessed: ../preprocessed_15_random_sample

logger:
  experiment: ../lightning_logs
  name: 15_random_sampled_baseline_testing

model:
  pretrained: false
  resume: false
  ckpt_path:
  lr: 0.001
  sw_batch_size: 4
  seed: 42

trainer:
  max_steps: 64600
  check_val_every_n_epoch: 5
  precision: bf16-mixed #32, 16
  accelerator: gpu
  devices: 1
  deterministic: true
  strategy: auto
  sync_batchnorm: true #false